"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](fg:#106ebe)\
$os\
$username\
[îƒ†](fg:#106ebe bg:#ffffff)\
$hostname\
[îƒ†](fg:#ffffff bg:#2b2d34)\
$directory\
$git_status\
[î‚´](fg:#2b2d34) \
"""

add_newline = true

[os]
style = "bg:#106ebe"
format = "[$symbol]($style)"
disabled = false

[username]
show_always = true
style_user = "bg:#106ebe fg:#ffffff"
style_root = "bg:#106ebe fg:#ff3333"
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_only = false
format = "[ ğŸ’» $hostname ](bg:#ffffff fg:#106ebe)"
disabled = false

[directory]
format = '[ ğŸ“‚ $path ](bg:#2b2d34 fg:#67fff0)'

[git_status]
format = '[$all_status](bg:#2b2d34 fg:#67fff0)'
diverged = 'ğŸ”€'
up_to_date = 'âœ…'
untracked = 'â“'
stashed = 'ğŸ“¥'
modified = 'âš ï¸'
staged = 'â•'
renamed = 'ğŸŸ¢'
deleted = 'ğŸ”´'
disabled = false
